# Generated by Django 6.0.4 on 2026-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_infrastructureproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureproject',
            name='location',
            field=models.CharField(choices=[('barangay_aplaya', 'Barangay Aplaya'), ('barangay_banaba', 'Barangay Banaba'), ('barangay_del_carmen', 'Barangay Del Carmen'), ('barangay_ibinac', 'Barangay Ibinac'), ('barangay_malomboy', 'Barangay Malomboy'), ('barangay_maligaya', 'Barangay Maligaya'), ('barangay_palalong', 'Barangay Palalong'), ('barangay_panghulo', 'Barangay Panghulo'), ('barangay_pinagsama', 'Barangay Pinagsama'), ('barangay_poblacion', 'Barangay Poblacion'), ('barangay_pulo', 'Barangay Pulo'), ('barangay_san_isidro', 'Barangay San Isidro'), ('barangay_telabastagan', 'Barangay Telabastagan')], help_text='Select barangay location', max_length=50),
        ),
    ]
