# Generated by Django 6.0.4 on 2026-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_infrastructureproject_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureproject',
            name='location',
            field=models.CharField(choices=[('bagong_sikat', 'Bagong Sikat'), ('bagting', 'Bagting'), ('bantug', 'Bantug'), ('bitulok', 'Bitulok (North Poblacion)'), ('bugnan', 'Bugnan'), ('calabasa', 'Calabasa'), ('camachile', 'Camachile'), ('cuyapa', 'Cuyapa'), ('ligaya', 'Ligaya'), ('macasandal', 'Macasandal'), ('malinao', 'Malinao'), ('pantoc', 'Pantoc'), ('pinamalisan', 'Pinamalisan'), ('south_poblacion', 'South Poblacion'), ('sawmill', 'Sawmill'), ('tagumpay', 'Tagumpay')], help_text='Select barangay location', max_length=50),
        ),
    ]
