# Generated by Django 6.0.4 on 2026-04-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_infrastructureproject_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureproject',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='draft', help_text='Current publication/approval status', max_length=50),
        ),
        migrations.AddField(
            model_name='infrastructureproject',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Admin comments for revision requests or rejections'),
        ),
        migrations.AddField(
            model_name='infrastructureproject',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the project was reviewed by admin', null=True),
        ),
        migrations.AddField(
            model_name='infrastructureproject',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
