"""Persist generated public reports and their PDF files."""

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import transaction
from django.utils import timezone
from django.utils.text import slugify

from apps.system.models import ProjectReport

from .pdf import build_individual_report_pdf, build_summary_report_pdf
from .services import (
    get_infrastructure_project_report_data,
    get_non_infrastructure_project_report_data,
)


INDIVIDUAL_GETTERS = {
    'infrastructure': get_infrastructure_project_report_data,
    'non_infrastructure': get_non_infrastructure_project_report_data,
}

REPORT_TYPES = {
    ('infrastructure', 'individual'): (
        ProjectReport.ReportType.INFRASTRUCTURE_INDIVIDUAL
    ),
    ('non_infrastructure', 'individual'): (
        ProjectReport.ReportType.NON_INFRASTRUCTURE_INDIVIDUAL
    ),
    ('infrastructure', 'summary'): (
        ProjectReport.ReportType.INFRASTRUCTURE_SUMMARY
    ),
    ('non_infrastructure', 'summary'): (
        ProjectReport.ReportType.NON_INFRASTRUCTURE_SUMMARY
    ),
}


def report_scope(project_report):
    value = project_report.report_type or ''
    if value.startswith('non_infrastructure_'):
        return 'non_infrastructure'
    if value.startswith('infrastructure_'):
        return 'infrastructure'
    return None


def _store_pdf(*, pdf_bytes, report_name, report_type, project, notes=''):
    timestamp = timezone.now().strftime('%Y%m%d-%H%M%S-%f')
    filename = f'{slugify(report_name)[:90] or "project-report"}-{timestamp}.pdf'
    storage_name = default_storage.save(
        f'reports/{report_type}/{filename}',
        ContentFile(pdf_bytes),
    )
    try:
        with transaction.atomic():
            return ProjectReport.objects.create(
                project=project,
                report_name=report_name,
                report_type=report_type,
                file_url=storage_name,
                notes=notes,
            )
    except Exception:
        default_storage.delete(storage_name)
        raise


def generate_individual_report(report_type, project_id, generated_by):
    report = INDIVIDUAL_GETTERS[report_type](project_id)
    pdf_bytes = build_individual_report_pdf(report_type, report)
    scope_label = (
        'Infrastructure' if report_type == 'infrastructure'
        else 'Non-Infrastructure'
    )
    report_name = f'{scope_label} Individual Report - {report["title"]}'
    notes = (
        f'Generated by {generated_by.username} from current published '
        f'revision {report["revision"].revision_number}.'
    )
    return _store_pdf(
        pdf_bytes=pdf_bytes,
        report_name=report_name,
        report_type=REPORT_TYPES[report_type, 'individual'],
        project=report['revision'].project,
        notes=notes,
    )


def generate_summary_report(
    report_type,
    summary,
    active_filters,
    generated_by,
):
    pdf_bytes = build_summary_report_pdf(
        report_type,
        summary,
        active_filters,
    )
    scope_label = (
        'Infrastructure' if report_type == 'infrastructure'
        else 'Non-Infrastructure'
    )
    report_name = f'{scope_label} Project Summary Report'
    filter_note = '; '.join(
        f'{label}: {value}' for label, value in active_filters
    ) or 'No filters'
    notes = (
        f'Generated by {generated_by.username} from current published '
        f'project revisions. {filter_note}.'
    )
    return _store_pdf(
        pdf_bytes=pdf_bytes,
        report_name=report_name,
        report_type=REPORT_TYPES[report_type, 'summary'],
        project=None,
        notes=notes,
    )
