# Generated by Django 6.0.4 on 2026-05-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_infrastructure', '0002_simplify_non_infrastructure_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noninfrastructureproject',
            name='source_of_fund',
            field=models.CharField(blank=True, help_text='e.g., GAA, PRDP', max_length=255),
        ),
    ]
