# Generated by Django 6.0.4 on 2026-05-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_infrastructure', '0003_alter_noninfrastructureproject_source_of_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='beneficiaries_description',
            field=models.TextField(blank=True, help_text='To whom is the service delivered? (e.g., students, farmers, PWD, elderly, etc.)'),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='budget_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget/Cost Amount (₱)'),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='results_achieved',
            field=models.TextField(blank=True, help_text='What were the results/outcomes achieved? (e.g., number of beneficiaries, skills gained, health improvements, etc.)'),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='service_description',
            field=models.TextField(blank=True, help_text='What service/program is being delivered?'),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='service_location_details',
            field=models.CharField(blank=True, help_text='Specific location/venue where service is delivered', max_length=255),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='service_period',
            field=models.CharField(blank=True, help_text='When is the service delivered? (e.g., weekly, monthly, semester, etc.)', max_length=255),
        ),
    ]
