# Generated by Django 6.0.4 on 2026-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_infrastructure', '0004_noninfrastructureproject_beneficiaries_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='service_time',
            field=models.TimeField(blank=True, help_text='Time of service delivery', null=True),
        ),
    ]
