# Generated by Django 6.0.4 on 2026-05-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_infrastructure', '0005_noninfrastructureproject_service_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noninfrastructureproject',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='noninfrastructureproject',
            name='review_comments',
        ),
        migrations.RemoveField(
            model_name='noninfrastructureproject',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='noninfrastructureproject',
            name='reviewed_by',
        ),
    ]
