# Generated by Django 6.0.4 on 2026-04-23 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('method', models.CharField(choices=[('creation', 'User Creation'), ('reset_link', 'Password Reset Link'), ('admin_edit', 'Admin Edit'), ('user_edit', 'User Self-Edit'), ('signal', 'System Change')], default='signal', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Change History',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['-changed_at'], name='core_passwo_changed_9ec6b5_idx'), models.Index(fields=['user', '-changed_at'], name='core_passwo_user_id_5b93f8_idx')],
            },
        ),
    ]
