# Generated by Django 6.0.4 on 2026-09-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='system.project'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='report_type',
            field=models.CharField(blank=True, choices=[('infrastructure_individual', 'Infrastructure Individual'), ('non_infrastructure_individual', 'Non-Infrastructure Individual'), ('infrastructure_summary', 'Infrastructure Summary'), ('non_infrastructure_summary', 'Non-Infrastructure Summary')], max_length=100, null=True),
        ),
    ]
