# Generated by Django 6.0.4 on 2026-04-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordchangehistory',
            new_name='system_pass_changed_86a39e_idx',
            old_name='core_passwo_changed_9ec6b5_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordchangehistory',
            new_name='system_pass_user_id_6bad2b_idx',
            old_name='core_passwo_user_id_5b93f8_idx',
        ),
    ]
