# Generated by Django 6.0.4 on 2026-07-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_core_passwo_changed_9ec6b5_idx_system_pass_changed_86a39e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('engineer', 'Engineering Office'), ('mayor', "Mayor's Office"), ('admin', 'Administration')], default='admin', max_length=20),
        ),
    ]
