# Generated by Django 6.0.4 on 2026-09-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_infrastructure_official_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='contractor_supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='fund_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='implementation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='implementation_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='procurement_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='project_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='project_type',
            field=models.CharField(choices=[('EVENT', 'Event / Activity'), ('PROGRAM', 'Program'), ('SERVICE', 'Service'), ('PROCUREMENT', 'Procurement / Acquisition'), ('TRAINING', 'Training / Seminar'), ('CAMPAIGN', 'Campaign / Initiative'), ('OTHER', 'Other')], default='EVENT', max_length=20),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='noninfrastructureproject',
            name='target_beneficiaries',
            field=models.TextField(blank=True, default=''),
        ),
    ]
