# Generated by Django 6.0.4 on 2026-08-12 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_userprofile_must_change_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('barangay', models.CharField(blank=True, max_length=200, null=True)),
                ('municipality', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
            },
        ),
        migrations.CreateModel(
            name='FundSource',
            fields=[
                ('fund_source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fund_source_code', models.CharField(max_length=100, unique=True)),
                ('fund_source_name', models.CharField(max_length=255, unique=True)),
                ('fund_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fund Source',
                'verbose_name_plural': 'Fund Sources',
            },
        ),
        migrations.CreateModel(
            name='ImplementingOffice',
            fields=[
                ('office_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Implementing Office',
                'verbose_name_plural': 'Implementing Offices',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureCategory',
            fields=[
                ('infrastructure_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=100, unique=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Infrastructure Category',
                'verbose_name_plural': 'Infrastructure Categories',
            },
        ),
        migrations.CreateModel(
            name='NonInfrastructureCategory',
            fields=[
                ('non_infrastructure_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=100, unique=True)),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Non-Infrastructure Category',
                'verbose_name_plural': 'Non-Infrastructure Categories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_type', models.CharField(default='gallery', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('is_visible_to_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
