# Generated by Django 6.0.4 on 2026-08-12 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_address_contractor_fundsource_implementingoffice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure_Project',
            fields=[
                ('infrastructure_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('infrastructure_code', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('infrastructure_title', models.CharField(max_length=255)),
                ('infrastructure_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.address')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.infrastructurecategory')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.contractor')),
                ('implementing_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.implementingoffice')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_project', to='system.project')),
            ],
            options={
                'verbose_name': 'Infrastructure Project',
                'verbose_name_plural': 'Infrastructure Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Non_Infrastructure_Project',
            fields=[
                ('non_infra_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('non_infra_name', models.CharField(max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_projects', to='system.address')),
                ('non_infra_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_projects', to='system.noninfrastructurecategory')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='non_infrastructure_project', to='system.project')),
            ],
            options={
                'verbose_name': 'Non-Infrastructure Project',
                'verbose_name_plural': 'Non-Infrastructure Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
