# Generated by Django 6.0.4 on 2026-09-24 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_simplify_infrastructure_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonInfrastructureProgressUpdate',
            fields=[
                ('progress_update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='', max_length=20)),
                ('proposed_status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('returned', 'Returned'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('non_infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_updates', to='system.noninfrastructureproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_progress_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_progress_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_non_infrastructure_progress_update',
                'ordering': ('-created_at', '-progress_update_id'),
            },
        ),
        migrations.CreateModel(
            name='NonInfrastructureEvidence',
            fields=[
                ('evidence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evidence_file', models.FileField(max_length=500, upload_to='non_infrastructure/evidence/%Y/%m/')),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_evidence_uploads', to=settings.AUTH_USER_MODEL)),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='system.noninfrastructureprogressupdate')),
            ],
            options={
                'db_table': 'system_non_infrastructure_evidence',
                'ordering': ('created_at', 'evidence_id'),
            },
        ),
    ]
