# Generated by Django 6.0.4 on 2026-09-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_noninfrastructureprogressupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noninfrastructureprogressupdate',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
