# Generated by Django 6.0.4 on 2026-09-24 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_noninfrastructureprogressupdate_review_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noninfrastructureprogressupdate',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noninfrastructureprogressupdate',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_infrastructure_progress_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noninfrastructureprogressupdate',
            name='publication_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_non_infrastructure_progress_update', to='system.projectrevision'),
        ),
    ]
