# Generated by Django 6.0.4 on 2026-08-12 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_seed_normalized_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('financial_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_visible_to_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finances', to='system.fundsource')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='system.infrastructure_project')),
            ],
            options={
                'verbose_name': 'Financial',
                'verbose_name_plural': 'Financial Records',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure_Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pre_bid_date', models.DateField(blank=True, null=True)),
                ('bidding_date', models.DateField(blank=True, null=True)),
                ('notice_award_date', models.DateField(blank=True, null=True)),
                ('notice_proceed_date', models.DateField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('contract_expiry_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='system.infrastructure_project')),
            ],
            options={
                'verbose_name': 'Infrastructure Schedule',
                'verbose_name_plural': 'Infrastructure Schedules',
            },
        ),
        migrations.CreateModel(
            name='Project_Inspection',
            fields=[
                ('inspection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inspection_date', models.DateField()),
                ('completion_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('findings', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspected_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_done', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='system.project')),
            ],
            options={
                'verbose_name': 'Project Inspection',
                'verbose_name_plural': 'Project Inspections',
            },
        ),
    ]
