# Generated by Django 6.0.4 on 2026-08-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_complete_infrastructure_data_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordchangehistory',
            options={'managed': False, 'ordering': ['-changed_at'], 'verbose_name_plural': 'Password Change History'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False, 'ordering': ['user__username']},
        ),
    ]
