# Generated by automated patch
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_backfill_physical_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('must_change_password', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='auth.user')),
            ],
            options={
                'verbose_name': 'User Flag',
                'verbose_name_plural': 'User Flags',
            },
        ),
    ]
