# Generated by Django 6.0.4 on 2026-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_add_userflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureProject',
            fields=[
                ('id', models.BigAutoField(db_column='infrastructure_id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='infrastructure_title', max_length=255)),
                ('description', models.TextField(db_column='infrastructure_description')),
                ('contractor_id', models.BigIntegerField(blank=True, db_column='contractor_id', null=True)),
                ('implementing_office_id', models.BigIntegerField(blank=True, db_column='implementing_office_id', null=True)),
                ('procurement_method', models.CharField(blank=True, max_length=50, null=True)),
                ('award_status', models.CharField(blank=True, max_length=50, null=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('cost_progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physical_progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'system_infrastructure_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonInfrastructureProject',
            fields=[
                ('non_infra_id', models.BigAutoField(db_column='non_infra_id', primary_key=True, serialize=False)),
                ('non_infra_name', models.CharField(db_column='non_infra_name', max_length=255)),
                ('event_date', models.DateField(blank=True, db_column='event_date', null=True)),
                ('start_time', models.TimeField(blank=True, db_column='start_time', null=True)),
                ('end_time', models.TimeField(blank=True, db_column='end_time', null=True)),
                ('description', models.TextField(db_column='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'system_non_infrastructure_project',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='infrastructure_project',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='infrastructure_project',
            name='implementing_office',
        ),
        migrations.AlterModelTable(
            name='passwordchangehistory',
            table='system_legacy_passwordchangehistory_archive',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='system_legacy_userprofile_archive',
        ),
    ]
