# Generated by Django 6.0.4 on 2026-08-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_infrastructureproject_noninfrastructureproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='project_image',
            name='image_name',
        ),
    ]
