# Generated by Django 6.0.4 on 2026-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_userflag_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_infrastructure_project',
            name='beneficiaries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='non_infrastructure_project',
            name='proponent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
