# Generated by Django 6.0.4 on 2026-08-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_non_infrastructure_project_beneficiaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='non_infrastructure_project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
    ]
