# Generated by Django 6.0.4 on 2026-08-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_non_infrastructure_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure_project',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.contractor'),
        ),
        migrations.AddField(
            model_name='infrastructure_project',
            name='implementing_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_projects', to='system.implementingoffice'),
        ),
    ]
