# Generated by Django 6.0.4 on 2026-08-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_infrastructure_project_contractor_and_more'),
        ('system', '0023_project_image_cover'),
    ]

    operations = [
    ]
