# Generated by Django 6.0.4 on 2026-08-21 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_merge_20260819_1820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPublicationRevision',
            fields=[
                ('revision_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_current_public_revision', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_revisions', to='system.project')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_project_publication_revisions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_publication_revisions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_project_publication_revisions', to=settings.AUTH_USER_MODEL)),
                ('supersedes_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_revisions', to='system.projectpublicationrevision')),
            ],
            options={
                'ordering': ['-revision_number'],
                'constraints': [models.UniqueConstraint(fields=('project', 'revision_number'), name='unique_project_publication_revision_number'), models.UniqueConstraint(condition=models.Q(('is_current_public_revision', True)), fields=('project',), name='one_current_public_revision_per_project'), models.CheckConstraint(condition=models.Q(('is_current_public_revision', False), ('status', 'published'), _connector='OR'), name='current_public_revision_must_be_published')],
            },
        ),
    ]
