# Generated by Django 6.0.4 on 2026-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_project_publication_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_image',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
