# Generated by Django 6.0.4 on 2026-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_userflag_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userflag',
            name='role',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('head', 'Head'), ('admin', 'Admin')], default='', help_text='Office responsibility used with department for authorization.', max_length=10),
        ),
    ]
