# Generated by Django 6.0.4 on 2026-09-14 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_userflag_role_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project_inspection',
            name='inspection_type',
            field=models.CharField(choices=[('progress', 'Progress'), ('routine', 'Routine'), ('final', 'Final'), ('special', 'Special')], default='routine', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionEvidence',
            fields=[
                ('inspection_evidence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('image', 'Photo'), ('document', 'Document')], max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('storage_name', models.CharField(max_length=500)),
                ('file_url', models.URLField(max_length=500)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='system.project_inspection')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Evidence',
                'verbose_name_plural': 'Inspection Evidence',
                'ordering': ('created_at', 'inspection_evidence_id'),
            },
        ),
    ]
