# Generated by Django 6.0.4 on 2026-09-14 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_inspection_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureProgressUpdate',
            fields=[
                ('progress_update_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_official_status', models.CharField(blank=True, choices=[('awarded', 'Awarded'), ('ongoing_bidding', 'Ongoing Bidding'), ('cancelled', 'Cancelled'), ('rebid', 'Re-bid'), ('completed', 'Completed')], default='', max_length=50)),
                ('new_official_status', models.CharField(blank=True, choices=[('awarded', 'Awarded'), ('ongoing_bidding', 'Ongoing Bidding'), ('cancelled', 'Cancelled'), ('rebid', 'Re-bid'), ('completed', 'Completed')], default='', max_length=50)),
                ('previous_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='system.infrastructure_project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_progress_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Infrastructure Progress Update',
                'verbose_name_plural': 'Infrastructure Progress Updates',
                'ordering': ('-created_at', '-progress_update_id'),
            },
        ),
    ]
