# Generated by Django 6.0.4 on 2026-09-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_infrastructure_progress_update_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureprogressupdate',
            name='supporting_inspections',
            field=models.ManyToManyField(blank=True, related_name='supported_progress_updates', to='system.project_inspection'),
        ),
    ]
