# Generated by Django 6.0.4 on 2026-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_infrastructure_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructureproject',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], default='draft', help_text='Current publication/approval status', max_length=50),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Admin comments for revision requests or rejections'),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the project was reviewed by admin', null=True),
        ),
        migrations.AlterField(
            model_name='infrastructureproject',
            name='revised_completion_date',
            field=models.DateField(blank=True, help_text="If there's extension of time", null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
