# Generated by Django 6.0.4 on 2026-05-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_infrastructureproject_publication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='bidding_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='disbursement_details',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='disbursements_to_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='noa_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='ntp_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='posting_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='prebid_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='review_comments',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='revised_completion_date',
        ),
        migrations.RemoveField(
            model_name='infrastructureproject',
            name='variation_orders',
        ),
    ]
